#!/usr/bin/python

# Author: Ondrej Tuma <mcbig@zeropage.cz>
# Copyright: This module has been placed in the BSD Licence.

"""
A minimal front end to CommonMarkParser, producing Tiny HTML.
"""

try:
    import locale
    locale.setlocale(locale.LC_ALL, '')
except:
    pass

from docutils.core import publish_cmdline, default_description
from docutils_tinyhtml import Writer
from docutils.parsers.rst import Parser as RstParser
from recommonmark.parser import CommonMarkParser
from recommonmark.transform import AutoStructify

description = ('Generates Tiny HTML documents from standalone '
               'MarkDown sources.  ' + default_description)


class Env(object):
    srcdir = ''


class ExtendCommonMarkParser(CommonMarkParser):
    settings_spec = RstParser.settings_spec

    def get_transforms(self):
        return CommonMarkParser.get_transforms(self) + [AutoStructify]


publish_cmdline(parser=ExtendCommonMarkParser(), writer=Writer(), writer_name='html',
                description=description, settings_overrides={'env': Env()})
